add Dockerfile and docker-compose.yml
ybloch/workshop-react-web pull request #1
Opened 2023-05-15 20:29 UTC by Elia-238

2023-05-16 03:43 UTC, ybloch requested changes

2023-05-16 03:43 UTC, ybloch commented on backend/main.py
> +        os.getenv("MONGODB_IP"), username=os.getenv("MONGODB_USERNAME"), password=os.getenv("MONGODB_PASSWORD"))
why not use the .env file?

2023-05-16 03:43 UTC, ybloch commented on docker-compose.yml
> +
no nginx?

2023-05-16 03:43 UTC, ybloch commented on frontend/Dockerfile
> +ENTRYPOINT ["npm", "start"]
There is no need to run this Dev server (`npm start`), it's only for development, you should use Nginx for serving the React static files (located in the build folder after running `build`).
This Nginx also should be proxy to the FastAPI

2023-05-17 18:39 UTC, Elia-238 commented on backend/main.py
> +        os.getenv("MONGODB_IP"), username=os.getenv("MONGODB_USERNAME"), password=os.getenv("MONGODB_PASSWORD"))
Because I don't pass it as an env file, I directly load it with the values. (This is how docker-compose does it at least, if we were working with k8s we could make a `config map` that would actually load an env file and we could use it for both deployment and development)

2023-05-17 21:21 UTC, Elia-238 commented on docker-compose.yml
> +
I think that way it will be more comfortable for the debug, and it will save them learning about Nginx as well.  
But anyway, I added. 😇

2023-05-18 03:50 UTC, merged